### ISSUE TITLE
ActiveRouteTagHelper

### ISSUE THREAD

**Issue by dotnetshadow** [bjcull/Pinch.SDK#2]
Hi there,

Great work with the taghelper, one minor issue I have found is that the outputted html still leaves **is-active-route** perhaps this can be removed

**Razor page**
```
<li is-active-route asp-controller="Account" asp-action="Register"><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
```

**HTML**
```
<li class="active" is-active-route="">
```

to 

```
<li class="active">
```

**UPDATE:**
Probably can fix this by updating the Process method
```
public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            base.Process(context, output);

            if (ShouldBeActive())
            {
                MakeActive(output);
            }

            // Remove attribute
            output.Attributes.RemoveAll("is-active-route");
        }
```

**Comment by bjcull** [comment]
Hey good catch, works like a charm. I've added your code in https://github.com/bjcull/Pinch.SDK/commit/ed1edd336ff0402f19c67306aa95da785b103b73

I've also updated the gist. Cheers :)
